# Generated by Django 4.2.2 on 2024-06-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
